### ISSUE TITLE
[tracker] Convert code-base to async/await

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#1536]
The code-base is heavily promise based. This issue is to convert all the promise-based code to instead use async/await.

This is a large task and will require being broken down into smaller pieces.

* [ ] Check and update babel transpilation steps to be async/await aware
* [ ] Convert src code to use await/async (leaving the tests as promise based initially)
* [ ] Once the src is converted and the existing test suite passes modify the tests to use async/awit too.

**Comment by apoorvasingh17** [comment]
@muffinresearch Hi, can I take this up?

**Comment by Divya063** [comment]
@muffinresearch I would like to work on this issue
> Check and update babel transpilation steps to be async/await aware

**Comment by muffinresearch** [comment]
@apoorvasingh17 @Divya063 we currently have this issue set aside for consideration as part of [outreachy](https://www.outreachy.org/). For now it will be preferable if you can find other issues to work on, however I will be sure to let you know if this issue is not going to be worked on as part of that program.

**Comment by rosygupta** [comment]
@muffinresearch I'd like to take this up as a part of the outreachy program.

**Comment by itaditya** [comment]
@muffinresearch I would like to fix this bug as part of the outreachy program

**Comment by AsmaSwapna** [comment]
@muffinresearch I'd like to take this up as a part of outreachy internship program round 15.

**Comment by pdehaan** [comment]
Should this be closed, or are there still some things left to `async..await`?

**Comment by rpl** [comment]
There are still 2 more pull requests: #1805 #1822
