### ISSUE TITLE
Refactor addons-linter documentation

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#2059]
This is a meta-issue containing a few papercuts that help drive the project a bit forward.

* [x] [Cleanup and update our README.md](https://github.com/mozilla/addons-linter/issues/2034)
* [x] [Cleanup our rules.md](https://github.com/mozilla/addons-linter/issues/1560)
* [ ] [Cleanup our documentation](https://github.com/mozilla/addons-linter/issues/2058)
* [ ] Generate our github-page directly from the docs/ folder instead of maintianing a separate `github-pages` branch. See https://blog.github.com/2016-08-17-simpler-github-pages-publishing/ for a way to configure this.

**Comment by muffinresearch** [comment]
@EnTeQuAk can we close this roll-up? I'm not sure how much we should worry about the last step, but the rest are filed as other issues.

**Comment by EnTeQuAk** [comment]
Yeah, we can just leave the remaining issue as a standalone open
