### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by fregante** [mozilla/addons-linter#3601]
`addons-linter` has [280 dependencies](https://npm.broofa.com/?q=addons-linter@2.13.1) ([47MB on disk](https://packagephobia.com/result?p=addons-linter)), which are almost half of [web-ext’s 610 dependencies](https://npm.broofa.com/?q=web-ext@5.5.0) ([72MB on disk](https://packagephobia.com/result?p=web-ext))

That's a lot.

Some dependencies can't be dropped, like eslint’s [108 dependencies](https://npm.broofa.com/?q=eslint@7.21.0) / [12MB](https://packagephobia.com/result?p=eslint), but others can.

I already sent #3600, hopefully I can send more, also improving sub-dependencies:

- [x] #3600 (10 dependencies -> 2)
- [ ] [mozilla/dispensary#864](https://github.com/mozilla/dispensary/issues/864) (80 dependencies -> 0)
- [x] [pierreinglebert/json-merge-patch#18](https://github.com/pierreinglebert/json-merge-patch/pull/18) (13 dependencies -> 1)
	- [x] Sub-dependency of [ajv-validator/ajv-merge-patch#45](https://github.com/ajv-validator/ajv-merge-patch/pull/45)
- [x] [sindresorhus/os-locale/pulls (author:fregante)](https://github.com/sindresorhus/os-locale/pulls?q=is%3Apr+author%3Afregante+drop) (26 dependencies -> 2)
- [x] [saadtazi/firefox-profile-js/pulls (author:fregante)](https://github.com/saadtazi/firefox-profile-js/pulls?q=is%3Apr+author%3Afregante+drop) (60 dependencies -> 12)

**Comment by fregante** [comment]
Also related: https://github.com/mozilla/dispensary/issues/864

**Comment by willdurand** [comment]
@fregante I see dispensary being mentioned here, I'll take a look as well but this week has been pretty busy for me. Thanks for your work!

**Comment by fregante** [comment]
Wow I didn't know you could assign non-members to issues 😅 unless I'm suddenly a Mozilla member without realizing

**Comment by willdurand** [comment]
haha, sorry. If you don't want to be assigned, it's also fine but we use assignees to know that a bug is actively worked on and give attribution during our standups as well.

**Comment by fregante** [comment]
Yeah no worries, I assumed that was the case

**Comment by fregante** [comment]
Only https://github.com/mozilla/dispensary/issues/864 is left out of this. 😌 Every other change will be received when you update the dependencies in this repo.

**Comment by willdurand** [comment]
@fregante FWIW, I started a patch to move the dispensary into addons-linter, see: https://github.com/mozilla/addons-linter/issues/869 and the PR attached to this issue.

**Comment by fregante** [comment]
@willdurand the intent was to keep it as a tool, not as a dependency. It you merge it 1:1 that won't solve the issue (in fact it preserves the `request` dependency)

Can you move it to a dev dependency while you're at it?

**Comment by willdurand** [comment]
> Can you move it to a dev dependency while you're at it?

Yep, in this patch or a follow-up (right now, it isn't going to make things worse)

**Comment by fregante** [comment]
Yesss, looking forward to the drop in dependency count!

**Comment by ioanarusiczki** [comment]
@willdurand Perhaps that's a qa not needed?

**Comment by willdurand** [comment]
> @willdurand Perhaps that's a qa not needed?

sorry, yes!
